name: ds-viz-plotly
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - async_generator=1.10
  - attrs=19.3.0
  - autopep8=1.4.4
  - backcall=0.1.0
  - bleach=3.1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.8
  - cycler=0.10.0
  - dash=1.4.1
  - dash-core-components=1.3.1
  - dash-html-components=1.0.1
  - dash-renderer=1.1.2
  - dash-table=4.4.1
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - flask=1.1.1
  - flask-compress=1.4.0
  - freetype=2.10.0
  - future=0.18.2
  - icu=64.2
  - idna=2.8
  - importlib_metadata=1.3.0
  - ipykernel=5.1.3
  - ipython=7.10.2
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - itsdangerous=1.1.0
  - jedi=0.15.2
  - jinja2=2.10.3
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter_client=5.3.3
  - jupyter_core=4.6.1
  - jupyter_server=0.1.1
  - jupyterlab=1.2.4
  - jupyterlab_pygments=0.1.0
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libffi=3.2.1
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libuv=1.33.1
  - llvm-openmp=9.0.0
  - markupsafe=1.1.1
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mistune=0.8.4
  - more-itertools=8.0.2
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nodejs=13.0.0
  - notebook=6.0.1
  - numpy=1.17.3
  - openssl=1.1.1d
  - pandas=0.25.3
  - pandoc=2.9.1
  - pandocfilters=1.4.2
  - parso=0.5.2
  - patsy=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - plotly=4.4.1
  - plotly-geo=1.0.0
  - plotly-orca=1.2.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - psutil=5.6.7
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - python=3.8.0
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.2
  - pyzmq=18.1.1
  - readline=8.0
  - requests=2.22.0
  - retrying=1.3.3
  - scipy=1.4.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=42.0.2
  - six=1.13.0
  - sqlite=3.30.1
  - statsmodels=0.10.2
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.7
  - voila=0.1.20
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11

